#pragma kernel BuildPatches
#pragma multi_compile_local __ ENABLE_FRUS_CULL
#pragma multi_compile_local __ ENABLE_HIZ_CULL
#pragma multi_compile_local __ BOUNDS_DEBUG

#include "Assets/ATGrassCloud/Shader/Lib/TerrainLib.hlsl"

StructuredBuffer<uint3> FinalTileList;
uniform StructuredBuffer<uint> _FinalTileListCount;
Texture2D<float4> _LODMapTexture;

ConsumeStructuredBuffer<RenderPatch> PatchConsumeList;
AppendStructuredBuffer<RenderPatch> CulledPatchList;

uniform float _HizDepthBias;
Texture2D<float4> _HizMap;
uniform float4 _HizMapSize;
uniform float4x4 _HizCameraMatrixVP;
uniform float3 _HizCameraPositionWS;
 
uniform float _BoundsHeightRedundance;
uniform int _SectorCountWorld;
#if BOUNDS_DEBUG
AppendStructuredBuffer<BoundsDebug> PatchBoundsList;
#endif

RenderPatch CreatePatch(uint3 tileLoc,uint2 patchOffset){
    uint lod = tileLoc.z;
    float tileMeterSize = GetTileSize(lod);
    float patchMeterSize = tileMeterSize / PATCH_COUNT_PER_TILE_IN_ROW;
    float2 tilePositionWS = GetTilePositionWS2(tileLoc.xy,lod);

    uint2 patchLoc = tileLoc.xy * PATCH_COUNT_PER_TILE_IN_ROW + patchOffset;
    float2 patchPositionWS = tilePositionWS + (patchOffset - (PATCH_COUNT_PER_TILE_IN_ROW - 1) * 0.5) * patchMeterSize;

    float2 minMaxHeight = SampleMinMaxHeight(patchPositionWS,lod + 2);
    minMaxHeight = minMaxHeight.rg * _TerrainWorldSize.y + float2(-_BoundsHeightRedundance,_BoundsHeightRedundance);
    RenderPatch patch;
    patch.lod = lod;
    patch.position = patchPositionWS;
    patch.minMaxHeight = minMaxHeight;
    patch.lodTrans = 0;
    // patch.lodTrans= uint4(patchOffset.xy,tileLoc.xy);
    return patch;
}

Bounds GetPatchBounds(RenderPatch patch){
    float halfSize = GetPatchExtent(patch.lod);
    #if ENABLE_SEAM
    halfSize *= 0.9;
    #endif
    Bounds bounds;
    float3 boundsMin,boundsMax;
    boundsMin.xz = patch.position - halfSize;
    boundsMax.xz = patch.position + halfSize;
    boundsMin.y = patch.minMaxHeight.x;
    boundsMax.y = patch.minMaxHeight.y;

    bounds.minPosition = boundsMin;
    bounds.maxPosition = boundsMax;
    return bounds;
}

bool IsOutSidePlane(float4 plane,float3 position){
    return dot(plane.xyz,position) + plane.w < 0; 
}

bool IsAABBOutSidePlane(float4 plane,float3 boundsMin,float3 boundsMax){
    return IsOutSidePlane(plane,boundsMin) &&
    IsOutSidePlane(plane,boundsMax) &&
    IsOutSidePlane(plane,float3(boundsMin.x,boundsMin.y,boundsMax.z)) &&
    IsOutSidePlane(plane,float3(boundsMin.x,boundsMax.y,boundsMin.z)) &&
    IsOutSidePlane(plane,float3(boundsMin.x,boundsMax.y,boundsMax.z)) &&
    IsOutSidePlane(plane,float3(boundsMax.x,boundsMin.y,boundsMax.z)) &&
    IsOutSidePlane(plane,float3(boundsMax.x,boundsMax.y,boundsMin.z)) &&
    IsOutSidePlane(plane,float3(boundsMax.x,boundsMin.y,boundsMin.z));
}
bool IsBoundsOutSidePlane(float4 plane,Bounds bounds){
    return IsAABBOutSidePlane(plane,bounds.minPosition,bounds.maxPosition);
}
bool FrustumCull(float4 planes[6],Bounds bounds){
    return IsBoundsOutSidePlane(planes[0],bounds) || 
    IsBoundsOutSidePlane(planes[1],bounds) || 
    IsBoundsOutSidePlane(planes[2],bounds) || 
    IsBoundsOutSidePlane(planes[3],bounds) || 
    IsBoundsOutSidePlane(planes[4],bounds) || 
    IsBoundsOutSidePlane(planes[5],bounds);
}


bool Cull(Bounds bounds){
    #if ENABLE_FRUS_CULL
    if(FrustumCull(_TerrainCameraFrustumPlanes,bounds)){
        return true;
    }
    #endif
    // #if ENABLE_HIZ_CULL
    // if(HizOcclusionCull(bounds)){
    //     return true;
    // }
    // #endif
    return false;
}

uint4 GetSectorBounds(uint3 nodeLoc){
    uint sectorCountPerNode = GetSectorCountPerTilePerRow(nodeLoc.z);
    uint2 sectorMin = nodeLoc.xy * sectorCountPerNode;
    return uint4(sectorMin,sectorMin + sectorCountPerNode-1);
}

uint GetLod(uint2 sectorLoc){
    if(sectorLoc.x < 0 || sectorLoc.y < 0 || sectorLoc.x >= _SectorCountWorld || sectorLoc.y >= _SectorCountWorld){
        return 0;
    }
    return round(_LODMapTexture[sectorLoc].r * MAX_TERRAIN_LOD);
}
 
void SetLodTrans(inout RenderPatch patch,uint3 nodeLoc,uint2 patchOffset){
    uint lod = nodeLoc.z;
    uint4 sectorBounds = GetSectorBounds(nodeLoc);
    int4 lodTrans = int4(0,0,0,0);
    if(patchOffset.x == 0){
        lodTrans.x = GetLod(sectorBounds.xy + int2(-1,0)) - lod;
    }
    if(patchOffset.y == 0){
        lodTrans.y = GetLod(sectorBounds.xy + int2(0,-1)) - lod;
    }
    if(patchOffset.x == 7){
        lodTrans.z = GetLod(sectorBounds.zw + int2(1,0)) - lod;
    }
    if(patchOffset.y == 7){
        lodTrans.w = GetLod(sectorBounds.zw + int2(0,1)) - lod;
    }
    patch.lodTrans = (uint4)max(0,lodTrans);
}


[numthreads(PATCH_COUNT_PER_TILE_IN_ROW,PATCH_COUNT_PER_TILE_IN_ROW,1)]
void BuildPatches(uint3 id : SV_DispatchThreadID,uint3 groupId:SV_GroupID,uint3 groupThreadId:SV_GroupThreadID) {
    uint tileId = groupId.x;
    uint3 tileLoc = FinalTileList[tileId];
    uint2 patchOffset = groupThreadId.xy;

    RenderPatch patch = CreatePatch(tileLoc,patchOffset);

    Bounds bounds = GetPatchBounds(patch);
    if (Cull(bounds)) {
        return;
    }
    // SetLodTrans(patch,tileLoc,patchOffset);
    CulledPatchList.Append(patch); 
    #if BOUNDS_DEBUG
    BoundsDebug boundsDebug;
    boundsDebug.bounds = bounds;
    boundsDebug.color = float4((bounds.minPosition + _TerrainWorldSize * 0.5) / _TerrainWorldSize ,1);
    boundsDebug.color.rgb = lerp(boundsDebug.color,GetDebugColor(tileLoc.z),0.8);
    PatchBoundsList.Append(boundsDebug);
    #endif
}