#pragma kernel BuildPatches

#pragma multi_compile __ AT_REVERSE_Z
#pragma multi_compile_local __ ENABLE_FRUS_CULL
#pragma multi_compile_local __ ENABLE_HIZ_CULL
#pragma multi_compile_local __ BOUNDS_DEBUG

#include "Assets/ATGrassCloud/Shader/Lib/DepthZLib.hlsl"
#include "Assets/ATGrassCloud/Shader/Lib/TerrainLib.hlsl"

StructuredBuffer<uint3> FinalTileList;
uniform StructuredBuffer<uint> _FinalTileListCount;
Texture2D<float4> _LODMapTexture;

ConsumeStructuredBuffer<RenderPatch> PatchConsumeList;
AppendStructuredBuffer<RenderPatch> CulledPatchList;

uniform float _HizDepthBias;
// Texture2D<float4> _HizMap;
// uniform float4 _HizMapSize;
// uniform float4x4 _HizCameraMatrixVP;
// uniform float3 _HizCameraPositionWS;
 
uniform float _BoundsHeightRedundance;
uniform int _SectorCountWorld;
#if BOUNDS_DEBUG
AppendStructuredBuffer<BoundsDebug> PatchBoundsList;
#endif

RenderPatch CreatePatch(uint3 tileLoc,uint2 patchOffset){
    uint lod = tileLoc.z;
    float tileMeterSize = GetTileSize(lod);
    float patchMeterSize = tileMeterSize / PATCH_COUNT_PER_TILE_IN_ROW;
    float2 tilePositionWS = GetTilePositionWS2(tileLoc.xy,lod);

    uint2 patchLoc = tileLoc.xy * PATCH_COUNT_PER_TILE_IN_ROW + patchOffset;
    float2 patchPositionWS = tilePositionWS + (patchOffset - (PATCH_COUNT_PER_TILE_IN_ROW - 1) * 0.5) * patchMeterSize;

    float2 minMaxHeight = SampleMinMaxHeight(patchPositionWS,lod + 2);
    minMaxHeight = minMaxHeight.rg * _TerrainWorldSize.y + float2(-_BoundsHeightRedundance,_BoundsHeightRedundance);
    RenderPatch patch;
    patch.lod = lod;
    patch.position = patchPositionWS;
    patch.minMaxHeight = minMaxHeight;
    patch.lodTrans = 0;
    // patch.lodTrans= uint4(patchOffset.xy,tileLoc.xy);
    return patch;
}

Bounds GetPatchBounds(RenderPatch patch){
    float halfSize = GetPatchExtent(patch.lod);
    #if ENABLE_SEAM
    halfSize *= 0.9;
    #endif
    Bounds bounds;
    float3 boundsMin,boundsMax;
    boundsMin.xz = patch.position - halfSize;
    boundsMax.xz = patch.position + halfSize;
    boundsMin.y = patch.minMaxHeight.x;
    boundsMax.y = patch.minMaxHeight.y;

    bounds.minPosition = boundsMin;
    bounds.maxPosition = boundsMax;
    return bounds;
}

bool IsOutSidePlane(float4 plane,float3 position){
    return dot(plane.xyz,position) + plane.w < 0; 
}

bool IsAABBOutSidePlane(float4 plane,float3 boundsMin,float3 boundsMax){
    return IsOutSidePlane(plane,boundsMin) &&
    IsOutSidePlane(plane,boundsMax) &&
    IsOutSidePlane(plane,float3(boundsMin.x,boundsMin.y,boundsMax.z)) &&
    IsOutSidePlane(plane,float3(boundsMin.x,boundsMax.y,boundsMin.z)) &&
    IsOutSidePlane(plane,float3(boundsMin.x,boundsMax.y,boundsMax.z)) &&
    IsOutSidePlane(plane,float3(boundsMax.x,boundsMin.y,boundsMax.z)) &&
    IsOutSidePlane(plane,float3(boundsMax.x,boundsMax.y,boundsMin.z)) &&
    IsOutSidePlane(plane,float3(boundsMax.x,boundsMin.y,boundsMin.z));
}
bool IsBoundsOutSidePlane(float4 plane,Bounds bounds){
    return IsAABBOutSidePlane(plane,bounds.minPosition,bounds.maxPosition);
}
bool FrustumCull(float4 planes[6],Bounds bounds){
    return IsBoundsOutSidePlane(planes[0],bounds) || 
    IsBoundsOutSidePlane(planes[1],bounds) || 
    IsBoundsOutSidePlane(planes[2],bounds) || 
    IsBoundsOutSidePlane(planes[3],bounds) || 
    IsBoundsOutSidePlane(planes[4],bounds) || 
    IsBoundsOutSidePlane(planes[5],bounds);
}

float SampleHiz(float2 uv,float mip,float mipTexSize){
    // uint2 coord = floor(uv * mipTexSize);
    // coord = min(coord,round(mipTexSize)-1);
    // return _DepthHiZTex.mips[mip][coord].r; 
    return depth_GetDepthHiZ(uv,(int)mip);
}


uint GetHizMip(Bounds boundsUVD){
    float3 minP = boundsUVD.minPosition;
    float3 maxP = boundsUVD.maxPosition;
    // return depth_GetHizMip(maxP.xy - minP.xy);
    float2 size = (maxP.xy - minP.xy) * _DepthHiZSize;
    uint2 mip2 = ceil(log2(size));
    uint mip = clamp(max(mip2.x,mip2.y),1,_DepthHiZMipmapCount - 1);
    return mip;
}


Bounds GetBoundsUVD(Bounds boundsWS){

    Bounds boundsUVD;

    float3 boundsMin = boundsWS.minPosition;
    float3 boundsMax = boundsWS.maxPosition;

    float3 p0 = depth_WorldPos2UVD(boundsMin);
    float3 p1 = depth_WorldPos2UVD(boundsMax);
    float3 p2 = depth_WorldPos2UVD(float3(boundsMin.x,boundsMin.y,boundsMax.z));
    float3 p3 = depth_WorldPos2UVD(float3(boundsMin.x,boundsMax.y,boundsMin.z));
    float3 p4 = depth_WorldPos2UVD(float3(boundsMin.x,boundsMax.y,boundsMax.z));
    float3 p5 = depth_WorldPos2UVD(float3(boundsMax.x,boundsMin.y,boundsMax.z));
    float3 p6 = depth_WorldPos2UVD(float3(boundsMax.x,boundsMax.y,boundsMin.z));
    float3 p7 = depth_WorldPos2UVD(float3(boundsMax.x,boundsMin.y,boundsMin.z));

    float3 min1 = min(min(p0,p1),min(p2,p3));
    float3 min2 = min(min(p4,p5),min(p6,p7));
    boundsUVD.minPosition = min(min1,min2);

    float3 max1 = max(max(p0,p1),max(p2,p3));
    float3 max2 = max(max(p4,p5),max(p6,p7));
    boundsUVD.maxPosition = max(max1,max2);
    return boundsUVD;
}

//Hiz Cull
bool HizOcclusionCull(Bounds bounds){
    bounds.minPosition -= normalize(bounds.minPosition - _DepthHiZCameraPosition) * _HizDepthBias;
    bounds.maxPosition -= normalize(bounds.maxPosition - _DepthHiZCameraPosition ) * _HizDepthBias;

    Bounds boundsUVD = GetBoundsUVD(bounds);

    uint mip = GetHizMip(boundsUVD);

    float3 minP = boundsUVD.minPosition;
    float3 maxP = boundsUVD.maxPosition;
    
    float mipTexSize = round(_DepthHiZSize / pow(2,mip));
    float d1 = SampleHiz(minP.xy,mip,mipTexSize); 
    float d2 = SampleHiz(maxP.xy,mip,mipTexSize); 
    float d3 = SampleHiz(float2(minP.x,maxP.y),mip,mipTexSize);
    float d4 = SampleHiz(float2(maxP.x,minP.y),mip,mipTexSize);
    
    #if AT_REVERSE_Z
    float depth = maxP.z;
    return d1 > depth && d2 > depth && d3 > depth && d4 > depth;
    #else
    float depth = minP.z;
    return d1 < depth && d2 < depth && d3 < depth && d4 < depth;
    #endif
}

bool Cull(Bounds bounds){
    #if ENABLE_FRUS_CULL
    if(FrustumCull(_TerrainCameraFrustumPlanes,bounds)){
        return true;
    }
    #endif
    #if ENABLE_HIZ_CULL
    if(HizOcclusionCull(bounds)){
        return true;
    }
    #endif
    return false;
}

uint4 GetSectorBounds(uint3 nodeLoc){
    uint sectorCountPerNode = GetSectorCountPerTilePerRow(nodeLoc.z);
    uint2 sectorMin = nodeLoc.xy * sectorCountPerNode;
    return uint4(sectorMin,sectorMin + sectorCountPerNode-1);
}

uint GetLod(uint2 sectorLoc){
    if(sectorLoc.x < 0 || sectorLoc.y < 0 || sectorLoc.x >= _SectorCountWorld || sectorLoc.y >= _SectorCountWorld){
        return 0;
    }
    return round(_LODMapTexture[sectorLoc].r * MAX_TERRAIN_LOD);
}
 
void SetLodTrans(inout RenderPatch patch,uint3 nodeLoc,uint2 patchOffset){
    uint lod = nodeLoc.z;
    uint4 sectorBounds = GetSectorBounds(nodeLoc);
    int4 lodTrans = int4(0,0,0,0);
    if(patchOffset.x == 0){
        lodTrans.x = GetLod(sectorBounds.xy + int2(-1,0)) - lod;
    }
    if(patchOffset.y == 0){
        lodTrans.y = GetLod(sectorBounds.xy + int2(0,-1)) - lod;
    }
    if(patchOffset.x == 7){
        lodTrans.z = GetLod(sectorBounds.zw + int2(1,0)) - lod;
    }
    if(patchOffset.y == 7){
        lodTrans.w = GetLod(sectorBounds.zw + int2(0,1)) - lod;
    }
    patch.lodTrans = (uint4)max(0,lodTrans);
}


[numthreads(PATCH_COUNT_PER_TILE_IN_ROW,PATCH_COUNT_PER_TILE_IN_ROW,1)]
void BuildPatches(uint3 id : SV_DispatchThreadID,uint3 groupId:SV_GroupID,uint3 groupThreadId:SV_GroupThreadID) {
    uint tileId = groupId.x;
    uint3 tileLoc = FinalTileList[tileId];
    uint2 patchOffset = groupThreadId.xy;

    RenderPatch patch = CreatePatch(tileLoc,patchOffset);

    Bounds bounds = GetPatchBounds(patch);
    if (Cull(bounds)) {
        return;
    }
    // SetLodTrans(patch,tileLoc,patchOffset);
    CulledPatchList.Append(patch); 
    #if BOUNDS_DEBUG
    BoundsDebug boundsDebug;
    boundsDebug.bounds = bounds;
    boundsDebug.color = float4((bounds.minPosition + _TerrainWorldSize * 0.5) / _TerrainWorldSize ,1);
    boundsDebug.color.rgb = pow( boundsDebug.color , 2.0) * lerp( GetDebugColor(tileLoc.z) , float3(1.0,1.0,1.0) , 0.25);
    Bounds boundsUVD = GetBoundsUVD(bounds);

    PatchBoundsList.Append(boundsDebug);
    #endif
}